apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: ai-agent-project
  source:
    repoURL: 'git@github.com:strsu/ai-lounge.git'
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

