apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ai-lounge
type: Opaque
data:
  POSTGRES_USER: bmFiaWppeW8=
  POSTGRES_PASSWORD: bmFiaWppeW9fcGFzc3dvcmQ=
  POSTGRES_DB: bmFiaWppeW8=
